cc=arm-fsl-linux-gnueabi-gcc

all:httpPost ipSwitch macDemo keyEvent readCpuId

httpPost:httpPost.c
	$(cc) httpPost.c -o httpPost

ipSwitch:ipSwitch.c
	$(cc) ipSwitch.c -o ipSwitch

macDemo:macDemo.c
	$(cc) macDemo.c -o macDemo

keyEvent:keyEvent.c
	$(cc) keyEvent.c -o keyEvent

readCpuId:readCpuId.c
	$(cc) readCpuId.c -o readCpuId
